{
  "swagger": "2.0",
  "info": {
    "description": "API documentation for Node",
    "version": "1.0.0",
    "title": "Node API"
  },
  "host": "localhost:3000",
  "basePath": "/api/v1",
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json",
    "application/xml"
  ],
  "produces": [
    "application/json",
    "application/xml"
  ],
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "security": [
    {
      "Bearer": []
    }
  ],
  "definitions": {
    "User": {
      "properties": {
        "username": {
          "type": "string",
          "default": "system_admin",
          "minLength": 3,
          "maxLength": 20
        },
        "password": {
          "type": "string",
          "default": "Admin@123",
          "minLength": 6,
          "maxLength": 100
        }
      }
    },
    "Employee": {
      "properties": {
        "username": {
          "type": "string"
        },
        "employeeNumber": {
          "type": "number"
        },
        "lastName": {
          "type": "string"
        },
        "firstName": {
          "type": "string"
        },
        "extension": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "officeCode": {
          "type": "string"
        },
        "jobTitle": {
          "type": "string"
        },
        "role": {
          "type": "string"
        }
      }
    },
    "Customer": {
      "properties": {
        "customerNumber": {
          "type": "number"
        },
        "customerName": {
          "type": "string"
        },
        "contactLastName": {
          "type": "string"
        },
        "contactFirstName": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        },
        "addressLine1": {
          "type": "string"
        },
        "addressLine2": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "postalCode": {
          "type": "string"
        },
        "country": {
          "type": "string"
        },
        "salesRepEmployeeNumber": {
          "type": "number"
        },
        "creditLimit": {
          "type": "number"
        }
      }
    },
    "Error": {
      "properties": {
        "statusCode": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        },
        "data": {
          "type": "object",
          "default": null
        },
        "errors": {
          "type": "string"
        }
      }
    }
  },
  "paths": {
    "/users/login": {
      "post": {
        "tags": [
          "Users"
        ],
        "security": [],
        "summary": "Login",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "401": {
            "description": "UNAUTHORIZED",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "NOT_FOUND",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "200": {
            "description": "SUCCESS",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "message": "SUCCESS",
                "data": {
                  "employeeNumber": 3,
                  "username": "system_admin",
                  "lastName": "Pham",
                  "firstName": "Jeff",
                  "extension": "",
                  "email": "jeffpham2906@gmail.com",
                  "jobTitle": "Leader Sales",
                  "role": "President",
                  "created_at": "2024-08-26T12:02:31.000Z",
                  "updated_at": "2024-08-26T12:02:31.000Z",
                  "permissions": [
                    {
                      "key": "<resource>",
                      "actions": [
                        {
                          "method": "<method>"
                        }
                      ]
                    }
                  ],
                  "token": "<generated token>"
                }
              }
            }
          }
        }
      }
    },
    "/users/register": {
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Register",
        "description": "Register a new user",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "New user details",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "username": {
                  "type": "string"
                },
                "password": {
                  "type": "string"
                },
                "employeeNumber": {
                  "type": "number"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "SUCCESS",
            "schema": {
              "$ref": "#/definitions/Employee"
            }
          },
          "401": {
            "description": "UNAUTHORIZED",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/customers": {
      "get": {
        "tags": [
          "Customers"
        ],
        "summary": "List Customers",
        "description": "Get a list of all users",
        "responses": {
          "200": {
            "description": "SUCCESS",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "message": "SUCCESS",
                "data": [
                  {
                    "customerNumber": 1,
                    "customerName": "John Doe",
                    "contactLastName": "Doe",
                    "contactFirstName": "John",
                    "phone": "123-456-7890",
                    "addressLine1": "123 Main St",
                    "addressLine2": "",
                    "city": "New York",
                    "state": "NY",
                    "postalCode": "10001",
                    "country": "USA",
                    "salesRepEmployeeNumber": 1002,
                    "creditLimit": 10000.0,
                    "createdAt": "2024-08-26T12:02:31.000Z",
                    "updatedAt": "2024-08-26"
                  }
                ]
              }
            }
          },
          "401": {
            "description": "UNAUTHORIZED",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "Customers"
        ],
        "summary": "Create a customer",
        "description": "Create a new customer",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Customer"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "SUCCESS",
            "examples": {
              "application/json": {
                "statusCode": 201,
                "message": "SUCCESS",
                "data": {
                  "customerNumber": 1,
                  "customerName": "John Doe",
                  "contactLastName": "Doe",
                  "contactFirstName": "John",
                  "phone": "123-456-7890",
                  "addressLine1": "123 Main St",
                  "addressLine2": "",
                  "city": "New York",
                  "state": "NY",
                  "postalCode": "10001",
                  "country": "USA",
                  "salesRepEmployeeNumber": 1002,
                  "creditLimit": 10000.0,
                  "createdAt": "2024-08-26T12:02:31.000Z",
                  "updatedAt": "2024-08-26"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/customers/{customerNumber}": {
      "patch": {
        "tags": [
          "Customers"
        ],
        "summary": "Update Customer",
        "description": "Update customer by customerNumber",
        "parameters": [
          {
            "in": "path",
            "name": "customerNumber",
            "type": "integer",
            "required": true,
            "description": "Customer Number"
          },
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Customer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "SUCCESS",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "message": "SUCCESS",
                "data": {
                  "customerNumber": 1,
                  "customerName": "John Doe",
                  "contactLastName": "Doe",
                  "contactFirstName": "John",
                  "phone": "123-456-7890",
                  "addressLine1": "123 Main St",
                  "addressLine2": "",
                  "city": "New York",
                  "state": "NY",
                  "postalCode": "10001",
                  "country": "USA",
                  "salesRepEmployeeNumber": 1002,
                  "creditLimit": 10000.0
                }
              }
            }
          },
          "401": {
            "description": "UNAUTHORIZED",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Customers"
        ],
        "summary": "Delete Customer",
        "description": "Delete customer by customerNumber",
        "parameters": [
          {
            "in": "path",
            "name": "customerNumber",
            "type": "integer",
            "required": true,
            "description": "customerNumber"
          }
        ],
        "responses": {
          "200": {
            "description": "SUCCESS",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "message": "SUCCESS"
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/employees": {
      "get": {
        "tags": [
          "Employees"
        ],
        "summary": "List Employees",
        "description": "Get a list of all employees",
        "responses": {
          "401": {
            "description": "UNAUTHORIZED",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "200": {
            "description": "Successful operation",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "message": "SUCCESS",
                "data": [
                  {
                    "employeeNumber": 1,
                    "lastName": "9999",
                    "firstName": "Default",
                    "extension": "",
                    "email": "Default",
                    "officeCode": "VN1",
                    "reportsTo": null,
                    "jobTitle": "Default",
                    "role": "Staff",
                    "created_at": "2024-08-26T12:02:31.000Z",
                    "updated_at": "2024-08-26T12:02:31.000Z",
                    "user": null,
                    "customers": []
                  }
                ]
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Employees"
        ],
        "summary": "Create Employee",
        "description": "Create a new employee",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Employee"
            }
          }
        ],
        "responses": {
          "401": {
            "description": "UNAUTHORIZED",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "201": {
            "description": "CREATED",
            "examples": {
              "application/json": {
                "statusCode": 201,
                "message": "Employee created successfully",
                "data": {
                  "employeeNumber": 1,
                  "lastName": "9999",
                  "firstName": "Default",
                  "extension": "",
                  "email": "Default",
                  "officeCode": "VN1",
                  "reportsTo": null,
                  "jobTitle": "Default",
                  "role": "Staff",
                  "created_at": "2024-08-26T12:02:31.000Z",
                  "updated_at": "2024-08-26T12:02:31.000Z",
                  "user": null,
                  "customers": []
                }
              }
            }
          }
        }
      }
    },
    "/employees/{employeeNumber}": {
      "patch": {
        "tags": [
          "Employees"
        ],
        "summary": "Update employee",
        "description": "Update employee by employeeNumber",
        "parameters": [
          {
            "in": "path",
            "name": "employeeNumber",
            "type": "integer",
            "required": true,
            "description": "Employee Number"
          },
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Employee"
            }
          }
        ],
        "responses": {
          "401": {
            "description": "UNAUTHORIZED",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "200": {
            "description": "SUCCESS",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "message": "Employee updated successfully",
                "data": {
                  "employeeNumber": 1,
                  "lastName": "9999",
                  "firstName": "Default",
                  "extension": "",
                  "email": "Default",
                  "officeCode": "VN1",
                  "reportsTo": null,
                  "jobTitle": "Default",
                  "role": "Staff",
                  "created_at": "2024-08-26T12:02:31.000Z",
                  "updated_at": "2024-08-26T12:02:31.000Z",
                  "user": null,
                  "customers": []
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Employees"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "employeeNumber",
            "type": "integer",
            "required": true,
            "description": "Employee Number"
          }
        ],
        "summary": "Delete employee",
        "description": "Delete employee",
        "responses": {
          "200": {
            "description": "Employee deleted"
          },
          "401": {
            "description": "UNAUTHORIZED",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  }
}